
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Inventory_Management_System.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Products
{

    public int productID { get; set; }

    public string product_Name { get; set; }

    public string product_Sku { get; set; }

    public string product_Quantity { get; set; }

    public Nullable<decimal> product_Price { get; set; }

    public string product_Description { get; set; }

    public int categoryID { get; set; }



    public virtual Category Category { get; set; }

}

}
